# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  couponbe:
    image: couponbe
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5273:5273
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
